services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gaming_network
    environment:
      # Root-User für die initiale Einrichtung
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword123
    command: mongod --auth
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./scripts/redis/users.acl:/data/users.acl
    networks:
      - gaming_network
    command: ["redis-server", "--aclfile", "/data/users.acl"]

networks:
  gaming_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: